name: pangeo
channels:
 - conda-forge
 - nodefaults
dependencies:
 - matplotlib-base
 - nb_conda_kernels
 - nbstripout
 - netcdf4
 - numpy
 - pandas
 - xarray
 - xarrayutils
 - xarray_leaflet
 - xarray-spatial
 - xcape
